version: '3.8'
services:
  dev-db:
    image: postgres:13
    volumes:
      - db_data:/data/db:ro
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    networks:
      - my_app
networks:
  my_app:
volumes:
  db_data:
